vich_uploader:
    db_driver: orm

    mappings:
        sites:
            uri_prefix: /uploads/sites
            upload_destination: '%kernel.project_dir%/public/uploads/sites'
        # topos:
        #     uri_prefix: /uploads/topos
        #     upload_destination: '%kernel.project_dir%/public/uploads/topos'
